### PR TITLE
Fix IllegalStateException in apt process

### PR DESCRIPTION
**Pull request by itmammoth**
Hi,
This is the same as [#214 in doma2](https://github.com/domaframework/doma/issues/214).
I don't know whether this repo is still maintained, anyway.

### CODE REVIEW

**Comment by nakamura-to** [comment]
Thanks for your feedback.
But we will fix only security vulnerabilities for Doma 1.
Could you consider to use Doma 2?

**Comment by itmammoth** [comment]
We'd love to, but our product is so big that we cannot make a quick migration to Doma2...

**Comment by nakamura-to** [comment]
We decided to change and clarify our maintenance policy. Now we accept any bug fixes. The new version Doma 1.38.1 includes this bug fix.
We have already released Doma 1.38.1. You can get it from the Maven central repository.

**Comment by nakamura-to** [comment]
Doma 1.38.1 doesn't work. Use Doma 1.38.2 instead of it.

**Comment by itmammoth** [comment]
Thanks!
You saved my life.

**Pull request merged**
